export const STATUS_VALUES = {
  NEW_MOS: 'NEW MOS',
  PREPARE_VEHICLE: 'PREPARE VEHICLE',
  ON_THE_WAY: 'ON THE WAY',
  ON_SITE: 'ON SITE',
  POD: 'POD',
  REPLAN_MOS_PROJECT: 'REPLAN MOS PROJECT',
  WAITING_PIC_FEEDBACK: 'WAITING PIC FEEDBACK',
  REPLAN_MOS_LSP_DELAY: 'REPLAN MOS DUE TO LSP DELAY',
  CLOSE_BY_RN: 'CLOSE BY RN',
  CANCEL_MOS: 'CANCEL MOS',
  NO_STATUS: 'NO STATUS',
};

export const STATUS_ORDERED_LIST = [
  STATUS_VALUES.NEW_MOS,
  STATUS_VALUES.PREPARE_VEHICLE,
  STATUS_VALUES.ON_THE_WAY,
  STATUS_VALUES.ON_SITE,
  STATUS_VALUES.POD,
  STATUS_VALUES.REPLAN_MOS_PROJECT,
  STATUS_VALUES.WAITING_PIC_FEEDBACK,
  STATUS_VALUES.REPLAN_MOS_LSP_DELAY,
  STATUS_VALUES.CLOSE_BY_RN,
  STATUS_VALUES.CANCEL_MOS,
  STATUS_VALUES.NO_STATUS,
];

export const STATUS_TRANSLATION_KEYS = {
  [STATUS_VALUES.NEW_MOS]: 'status.newMos',
  [STATUS_VALUES.PREPARE_VEHICLE]: 'status.prepareVehicle',
  [STATUS_VALUES.ON_THE_WAY]: 'status.inTransit',
  [STATUS_VALUES.ON_SITE]: 'status.onSite',
  [STATUS_VALUES.POD]: 'status.pod',
  [STATUS_VALUES.REPLAN_MOS_PROJECT]: 'status.projectReschedule',
  [STATUS_VALUES.WAITING_PIC_FEEDBACK]: 'status.waitingFeedback',
  [STATUS_VALUES.REPLAN_MOS_LSP_DELAY]: 'status.rescheduleLsp',
  [STATUS_VALUES.CLOSE_BY_RN]: 'status.rnClosed',
  [STATUS_VALUES.CANCEL_MOS]: 'status.cancelMos',
  [STATUS_VALUES.NO_STATUS]: 'status.noStatus',
};

export const STATUS_FALLBACK_LABELS = {
  [STATUS_VALUES.NEW_MOS]: '新建MOS',
  [STATUS_VALUES.PREPARE_VEHICLE]: '准备车辆',
  [STATUS_VALUES.ON_THE_WAY]: '开始运输',
  [STATUS_VALUES.ON_SITE]: '已到达',
  [STATUS_VALUES.POD]: 'POD',
  [STATUS_VALUES.REPLAN_MOS_PROJECT]: '项目重排(Project)',
  [STATUS_VALUES.WAITING_PIC_FEEDBACK]: '等待图片反馈',
  [STATUS_VALUES.REPLAN_MOS_LSP_DELAY]: '重新排期(LSP)',
  [STATUS_VALUES.CLOSE_BY_RN]: 'RN关闭',
  [STATUS_VALUES.CANCEL_MOS]: '取消MOS',
  [STATUS_VALUES.NO_STATUS]: '无状态',
};

export const STATUS_ALIAS_MAP = {
  [STATUS_VALUES.NEW_MOS]: STATUS_VALUES.NEW_MOS,
  'NEW MOS': STATUS_VALUES.NEW_MOS,
  '新建MOS': STATUS_VALUES.NEW_MOS,
  '新 MOS': STATUS_VALUES.NEW_MOS,
  'MOS BARU': STATUS_VALUES.NEW_MOS,
  'MOS Baru': STATUS_VALUES.NEW_MOS,

  [STATUS_VALUES.PREPARE_VEHICLE]: STATUS_VALUES.PREPARE_VEHICLE,
  '准备车辆': STATUS_VALUES.PREPARE_VEHICLE,
  'PREPARE VEHICLE': STATUS_VALUES.PREPARE_VEHICLE,
  'SIAPKAN KENDARAAN': STATUS_VALUES.PREPARE_VEHICLE,
  'PREPARE_VEHICLE': STATUS_VALUES.PREPARE_VEHICLE,

  [STATUS_VALUES.ON_THE_WAY]: STATUS_VALUES.ON_THE_WAY,
  'ON THE WAY': STATUS_VALUES.ON_THE_WAY,
  'IN TRANSIT': STATUS_VALUES.ON_THE_WAY,
  'START TRANSPORT': STATUS_VALUES.ON_THE_WAY,
  '开始运输': STATUS_VALUES.ON_THE_WAY,
  '运输中': STATUS_VALUES.ON_THE_WAY,
  '在途': STATUS_VALUES.ON_THE_WAY,
  'SEDANG DIKIRIM': STATUS_VALUES.ON_THE_WAY,
  'MULAI PENGIRIMAN': STATUS_VALUES.ON_THE_WAY,
  'Mulai Pengiriman': STATUS_VALUES.ON_THE_WAY,

  [STATUS_VALUES.ON_SITE]: STATUS_VALUES.ON_SITE,
  'ON SITE': STATUS_VALUES.ON_SITE,
  'ARRIVED': STATUS_VALUES.ON_SITE,
  '现场': STATUS_VALUES.ON_SITE,
  '已到达': STATUS_VALUES.ON_SITE,
  '到达': STATUS_VALUES.ON_SITE,
  'SUDAH TIBA': STATUS_VALUES.ON_SITE,
  'TIBA DI LOKASI': STATUS_VALUES.ON_SITE,
  'DI LOKASI': STATUS_VALUES.ON_SITE,

  [STATUS_VALUES.POD]: STATUS_VALUES.POD,
  'PROOF OF DELIVERY': STATUS_VALUES.POD,

  [STATUS_VALUES.REPLAN_MOS_PROJECT]: STATUS_VALUES.REPLAN_MOS_PROJECT,
  'REPLAN MOS PROJECT': STATUS_VALUES.REPLAN_MOS_PROJECT,
  '项目重排(Project)': STATUS_VALUES.REPLAN_MOS_PROJECT,
  'PENJADWALAN ULANG PROYEK': STATUS_VALUES.REPLAN_MOS_PROJECT,

  [STATUS_VALUES.WAITING_PIC_FEEDBACK]: STATUS_VALUES.WAITING_PIC_FEEDBACK,
  'WAITING PIC FEEDBACK': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  'WAITING PHOTO FEEDBACK': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  '等待 PIC 反馈': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  '等待PIC反馈': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  '等待图片反馈': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  'MENUNGGU UMPAN BALIK PIC': STATUS_VALUES.WAITING_PIC_FEEDBACK,
  'MENUNGGU UMPAN BALIK FOTO': STATUS_VALUES.WAITING_PIC_FEEDBACK,

  [STATUS_VALUES.REPLAN_MOS_LSP_DELAY]: STATUS_VALUES.REPLAN_MOS_LSP_DELAY,
  'REPLAN MOS DUE TO LSP DELAY': STATUS_VALUES.REPLAN_MOS_LSP_DELAY,
  '重新排期(LSP)': STATUS_VALUES.REPLAN_MOS_LSP_DELAY,
  'PENJADWALAN ULANG (LSP)': STATUS_VALUES.REPLAN_MOS_LSP_DELAY,

  [STATUS_VALUES.CLOSE_BY_RN]: STATUS_VALUES.CLOSE_BY_RN,
  'CLOSE BY RN': STATUS_VALUES.CLOSE_BY_RN,
  'RN关闭': STATUS_VALUES.CLOSE_BY_RN,
  'RN DITUTUP': STATUS_VALUES.CLOSE_BY_RN,

  [STATUS_VALUES.CANCEL_MOS]: STATUS_VALUES.CANCEL_MOS,
  'CANCEL MOS': STATUS_VALUES.CANCEL_MOS,
  '取消MOS': STATUS_VALUES.CANCEL_MOS,
  'BATALKAN MOS': STATUS_VALUES.CANCEL_MOS,
  [STATUS_VALUES.NO_STATUS]: STATUS_VALUES.NO_STATUS,
  'NO STATUS': STATUS_VALUES.NO_STATUS,
  'No Status': STATUS_VALUES.NO_STATUS,
  'no status': STATUS_VALUES.NO_STATUS,
  'NO_STATUS': STATUS_VALUES.NO_STATUS,
  '无状态': STATUS_VALUES.NO_STATUS,
  '無狀態': STATUS_VALUES.NO_STATUS,
  '沒有狀態': STATUS_VALUES.NO_STATUS,
  '没有状态': STATUS_VALUES.NO_STATUS,
  'TANPA STATUS': STATUS_VALUES.NO_STATUS,
};

export const ROLE_DEFINITIONS = {
  lsp: {
    key: 'lsp',
    label: 'LSP',
    description: 'LSP',
    permissions: {
      canEdit: true,
      canDelete: false,
      allowRemark: true,
      allowPhoto: true,
      requireStatusSelection: true,
      statusOptions: [
        STATUS_VALUES.PREPARE_VEHICLE,
        STATUS_VALUES.ON_THE_WAY,
        STATUS_VALUES.REPLAN_MOS_LSP_DELAY,
      ],
    },
    statusHighlights: [
      { status: STATUS_VALUES.NEW_MOS },
      { status: STATUS_VALUES.CANCEL_MOS },
      { status: STATUS_VALUES.CLOSE_BY_RN },
      { status: STATUS_VALUES.WAITING_PIC_FEEDBACK },
    ],
    users: [
      { id: 'lsp-operator-01', name: 'LSP Operator 01', password: 'LSP-123456' },
      { id: 'lsp-operator-02', name: 'LSP Operator 02', password: 'LSP-234567' },
      { id: 'lsp-operator-03', name: 'LSP Operator 03', password: 'LSP-345678' },
      { id: 'lsp-operator-04', name: 'LSP Operator 04', password: 'LSP-456789' },
      { id: 'lsp-operator-05', name: 'LSP Operator 05', password: 'LSP-567890' },
      { id: 'lsp-operator-06', name: 'LSP Operator 06', password: 'LSP-678901' },
      { id: 'lsp-operator-07', name: 'LSP Operator 07', password: 'LSP-789012' },
      { id: 'lsp-operator-08', name: 'LSP Operator 08', password: 'LSP-890123' },
      { id: 'lsp-operator-09', name: 'LSP Operator 09', password: 'LSP-901234' },
      { id: 'lsp-operator-10', name: 'LSP Operator 10', password: 'LSP-012345' },
    ],
  },
  customer: {
    key: 'customer',
    label: '项目组',
    description: 'Project Team',
    permissions: {
      canEdit: true,
      canDelete: true,
      allowRemark: true,
      allowPhoto: false,
      requireStatusSelection: false,
      statusOptions: [
        STATUS_VALUES.REPLAN_MOS_PROJECT,
        STATUS_VALUES.CANCEL_MOS,
        STATUS_VALUES.CLOSE_BY_RN,
      ],
    },
    statusHighlights: [
      { status: STATUS_VALUES.NEW_MOS },
      { status: STATUS_VALUES.POD },
    ],
    users: [
      { id: 'project-team-01', name: 'Project Team 01', password: 'HW-PROJ-888888' },
      { id: 'project-team-02', name: 'Project Team 02', password: 'HW-PROJ-777777' },
      { id: 'project-team-03', name: 'Project Team 03', password: 'HW-PROJ-666666' },
      { id: 'project-team-04', name: 'Project Team 04', password: 'HW-PROJ-555555' },
      { id: 'project-team-05', name: 'Project Team 05', password: 'HW-PROJ-444444' },
      { id: 'project-team-06', name: 'Project Team 06', password: 'HW-PROJ-333333' },
      { id: 'project-team-07', name: 'Project Team 07', password: 'HW-PROJ-222222' },
      { id: 'project-team-08', name: 'Project Team 08', password: 'HW-PROJ-111111' },
      { id: 'project-team-09', name: 'Project Team 09', password: 'HW-PROJ-999999' },
      { id: 'project-team-10', name: 'Project Team 10', password: 'HW-PROJ-135791' },
    ],
  },
  transportManager: {
    key: 'transportManager',
    label: '运输经理',
    description: 'Transport Manager',
    permissions: {
      canEdit: true,
      canDelete: true,
      allowRemark: true,
      allowPhoto: true,
      requireStatusSelection: false,
      statusOptions: STATUS_ORDERED_LIST.filter(
        (status) => status !== STATUS_VALUES.NO_STATUS
      ),
    },
    statusHighlights: [
      { status: STATUS_VALUES.NEW_MOS },
      { status: STATUS_VALUES.CANCEL_MOS },
      { status: STATUS_VALUES.CLOSE_BY_RN },
      { status: STATUS_VALUES.REPLAN_MOS_PROJECT },
      { status: STATUS_VALUES.REPLAN_MOS_LSP_DELAY },
      { status: STATUS_VALUES.PREPARE_VEHICLE },
      { status: STATUS_VALUES.ON_THE_WAY },
    ],
    users: [
      { id: 'tm-lead-01', name: 'Transport Manager 01', password: 'HW-LSM-888888' },
      { id: 'tm-lead-02', name: 'Transport Manager 02', password: 'HW-LSM-777234' },
      { id: 'tm-lead-03', name: 'Transport Manager 03', password: 'HW-LSM-666345' },
      { id: 'tm-lead-04', name: 'Transport Manager 04', password: 'HW-LSM-555456' },
      { id: 'tm-lead-05', name: 'Transport Manager 05', password: 'HW-LSM-444567' },
      { id: 'tm-lead-06', name: 'Transport Manager 06', password: 'HW-LSM-333678' },
      { id: 'tm-lead-07', name: 'Transport Manager 07', password: 'HW-LSM-222789' },
      { id: 'tm-lead-08', name: 'Transport Manager 08', password: 'HW-LSM-111890' },
      { id: 'tm-lead-09', name: 'Transport Manager 09', password: 'HW-LSM-999012' },
      { id: 'tm-lead-10', name: 'Transport Manager 10', password: 'HW-LSM-246801' },
      { id: 'tm-lead-11', name: 'Transport Manager 11', password: 'HW-LSM-357902' },
      { id: 'tm-lead-12', name: 'Transport Manager 12', password: 'HW-LSM-468013' },
      { id: 'tm-lead-13', name: 'Transport Manager 13', password: 'HW-LSM-579124' },
      { id: 'tm-lead-14', name: 'Transport Manager 14', password: 'HW-LSM-680235' },
      { id: 'tm-lead-15', name: 'Transport Manager 15', password: 'HW-LSM-791346' },
      { id: 'tm-lead-16', name: 'Transport Manager 16', password: 'HW-LSM-802457' },
      { id: 'tm-lead-17', name: 'Transport Manager 17', password: 'HW-LSM-913568' },
      { id: 'tm-lead-18', name: 'Transport Manager 18', password: 'HW-LSM-024679' },
      { id: 'tm-lead-19', name: 'Transport Manager 19', password: 'HW-LSM-135680' },
      { id: 'tm-lead-20', name: 'Transport Manager 20', password: 'HW-LSM-246791' },
    ],
  },
};

export const ROLE_LIST = Object.values(ROLE_DEFINITIONS);
